version: '3'

services: 
    db:
        image: mysql:5.7
        #command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true        
        networks: 
            - dbnetwork
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./dbdata:/var/lib/mysql
            - ./mysql:/docker-entrypoint-initdb.d

    app:
        build: 
            context: ./node
        container_name: app
        entrypoint: dockerize -wait tcp://db:3306 node index.js
        depends_on:
            - db
        ports:  
            - "3000:3000"
        networks: 
            - dbnetwork
            - appnetwork
        volumes: 
            - ./node:/usr/src/app
            - /usr/src/app/node_modules
        tty: true
    nginx:
        build:             
            context: ./nginx
        container_name: nginx
        entrypoint: dockerize -wait http://app:3000 nginx -g 'daemon off;'
        depends_on:
            - app
        ports:  
            - "8000:80"
        networks: 
            - appnetwork    
networks: 
    dbnetwork:
        driver: bridge
    appnetwork:
        driver: bridge
